import { Inter } from "next/font/google";
import styles from "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-white" lang="en">

      <body className={inter.className}>
       <div className={styles.container}>
       <Navbar></Navbar> 
        {children}
       </div> 
        
        </body>
    </html>
  );
}
